#  .----------------.  .----------------.  .----------------.  .----------------.
#| .--------------. || .--------------. || .--------------. || .--------------. |
#| |      __      | || |     ______   | || | ____    ____ | || |   ______     | |
#| |     /  \     | || |   .' ___  |  | || ||_   \  /   _|| || |  |_   __ \   | |
#| |    / /\ \    | || |  / .'   \_|  | || |  |   \/   |  | || |    | |__) |  | |
#| |   / ____ \   | || |  | |         | || |  | |\  /| |  | || |    |  ___/   | |
#| | _/ /    \ \_ | || |  \ `.___.'\  | || | _| |_\/_| |_ | || |   _| |_      | |
#| ||____|  |____|| || |   `._____.'  | || ||_____||_____|| || |  |_____|     | |
#| |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'
#  Copyright (c) 2024 to OfirTIM Hoffman (OfirHoffman@outlook.com) && Lior Slakman (me@voigon.dev).
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at

#  https://www.apache.org/licenses/LICENSE-2.0

#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# AdvancedChatManagerPlus is a plugin created to control 90% of your server's chat, allowing superUsers to block, clean and rerun chat events.
# ACMP has 40 different features built in that can be disabled/enabled any time, with smart rethrowal system always looking for plugin collisions,
# system indifferences and smart checkout if anything does not go together in the right terms.
# Although the market is filled with various different chat control systems, ACMP tries to provide the best and highest adaptability and compatibility
# to your server, providing smooth experience to players like hover-able messages, clickable messages and some other fun functionality;

# Below is a section of settings that by default generated by the plugin so it can generally run in peaceful maneuverability.
# Please be cautious with each setting as 1 simple change can bug the whole system and resetting the plugin to its fallback default.
# If the plugin can not load properly with updated configuration, we have a solution that allows using a fall-back configuration.
configuration:
  # **The version option should stay untouched if you don't know what it does in terms of code**.
  version: 45
  # Enable/Disable auto-reload function.
  # Please notice if this turns on, every 4-5 seconds the config will be automatically reloaded,
  # and the command "/acmp reload" will be disabled by default to avoid reloading collisions.
  auto-reload: true

  # Below is the configuration fall-back system details
  fall-back:
    # Enables/Disables the fall-back functionality.
    enabled: true
    # fall-back files can ONLY be YAML files, otherwise it will not load (Not even json).
    file-name: "default-config"

# Below are settings for logging.
logger:
  # Sets verbose in the console to appear more detailed in terms of data wise info.
  # There are 3 verbose priorities: ALL, MID & LOW.
  # While ALL shows *all* info in console in terms of messages, database connections, info fetching and such,
  # MID & LOW show only a partial info about only critical data & errors.
  verbose: LOW
  log-db-connections: true

  log-db-connections-number: true

# Sets the default locale for most players.
# This plugin allows multi-language platforming meaning players can change their language ingame for this plugin specifically.
## !! IMPORTANT DETAIL BELLOW !! ##
# **Please avoid switching locales by only reloading the configuration file (/acmp reload) and only reload or restart the entire server,
# as the language system must be loaded by the server on startup and not by the plugin mid-session.**
default-locale: "EN_US"

################################################################
#   _____            _             ____                        #
#  |  __ \          | |           |  _ \                       #
#  | |  | |   __ _  | |_    __ _  | |_) |   __ _   ___    ___  #
#  | |  | |  / _` | | __|  / _` | |  _ <   / _` | / __|  / _ \ #
#  | |__| | | (_| | | |_  | (_| | | |_) | | (_| | \__ \ |  __/ #
#  |_____/   \__,_|  \__|  \__,_| |____/   \__,_| |___/  \___| #
#                                                              #
################################################################
# Database connection is rather simple to use, ACMP allows the following options for database connectivity:
# Flat file, MySQL, SQLite, MongoDB.
#
# If connection won't be established the plugin will fall-back to the fall-back-db setting, allowing the plugin to continue its session.
## !! IMPORTANT DETAIL BELLOW !! ##
# The database connection can only be established when the plugin starts up, and not beforehand.
# avoid trying to connect before reloading or restarting the server, it will not work and the plugin will go to fall-back.
database:
  fall-back-db: SQLITE
  database-type: FLATFILE

  ## !! Credentials Db Authenticating !! ##
  address: "localhost"
  port: "3306"
  user: "user"
  password: "root"

#############################
#    _____ _           _    #
#   / ____| |         | |   #
#  | |    | |__   __ _| |_  #
#  | |    | '_ \ / _` | __| #
#  | |____| | | | (_| | |_  #
#  \_____|_| |_|\__,_|\__|  #
#                           #
#############################
# The chat section plays a small part of the plugin's functionality, this section is only for chat designing and such.
# Please make sure that you use the right syntax for each system, otherwise the whole chat will go to fallback mode.

# Placeholders are helpful if you want to make your chat as customizable as possible, allowing you to have so many types
# of placeholders, and in the near future we plan to implement PlaceHolderAPI into this amazing chat system.
# Placeholders are for in-message replacements, meaning it is not related to players prefixes and formats.
# example: [Owner] OfirTIM: Hello everyone! I have gotten the famous [item]! - this will replace the placeholder with the item in hand.
placeholders:
  item-in-hand:
    allow: true
    show-air: false
    placeholder: "[item]"