#  .----------------.  .----------------.  .----------------.  .----------------.
#| .--------------. || .--------------. || .--------------. || .--------------. |
#| |      __      | || |     ______   | || | ____    ____ | || |   ______     | |
#| |     /  \     | || |   .' ___  |  | || ||_   \  /   _|| || |  |_   __ \   | |
#| |    / /\ \    | || |  / .'   \_|  | || |  |   \/   |  | || |    | |__) |  | |
#| |   / ____ \   | || |  | |         | || |  | |\  /| |  | || |    |  ___/   | |
#| | _/ /    \ \_ | || |  \ `.___.'\  | || | _| |_\/_| |_ | || |   _| |_      | |
#| ||____|  |____|| || |   `._____.'  | || ||_____||_____|| || |  |_____|     | |
#| |              | || |              | || |              | || |              | |
#| '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '----------------'  '----------------'
#
# AdvancedChatManagerPlus is a plugin created to control 90% of your server's chat, allowing superUsers to block, clean and rerun chat events.
# ACMP has 40 different features built in that can be disabled/enabled any time, with smart rethrowal system always looking for plugin collisions,
# system indifferences and smart checkout if anything does not go together in the right terms.